config/routes.rb
# encoding: UTF-8

Homepage::Application.routes.draw do
  # Static single pages
  get 'about',          :to => 'static_pages#about_us', :as => 'about_us'
  get 'services',       :to => 'static_pages#services'

  # Users
  devise_for :users, :skip => [:passwords, :registrations]

  # Contact
  get 'contact',        :to => 'enquiries#new'
  resources :enquiries

  # Blog
  get 'blog', :to => 'posts#index'

  get 'blog/:year/:month/:id' => 'posts#show',
    :as => 'friendly_post_show',
    :constraints => { :year => /\d{4}/,
                      :month => /(0[1-9]|1[012])/,
                      :id => /\S+/ }

  get 'blog/:year(/:month)' => 'posts#published_at',
    :as => "post_published_at",
    :constraints => { :year => /\d{4}/, :month => /(0[1-9]|1[012])/ }

  get 'posts/tagged/:tag_name' => 'posts#tagged', :as => "post_tags"

  resources :posts do
    resources :comments
  end

  # Root path
  root :to => "static_pages#home"
end

app/views/content_columns/_home.html.erb
<div class="cols">
  <div class="cl">&nbsp;</div>

  <!-- Col -->
  <div class="col col2">
    <h2 class="border">What we do</h2>
    <div class="entry justify">
      <p>
        Gnomeslab positions itself as a specialist in providing both services and solutions based on Ruby 
        technologies (e.g. Ruby on Rails, Sinatra, Rack), targeted at different kinds of organizations, 
        both private and public.
        We are mainly oriented towards the development of web facing applications, services and products. 
        <%= link_to "more", services_path %>
      </p>
    </div>
  </div>
  <!-- End Col -->

  <!-- Col -->
  <div class="col col2">
    <h2 class="border">Meet the team</h2>
    <div class="entry justify">
      <p>
        We have a young and dynamic team of IT professionals, whose skills range from <i>Project Management</i>, 
        through <i>Product Development</i> to <i>Agile Software Development</i>.
      </p>
      <p>
        At Gnomeslab we value continuous learning and creative professionals that are able to solve complex 
        business problems with elegance and proficiency. <%= link_to "more", "#{about_us_path}#team" %>
      </p>
    </div>
  </div>
  <!-- End Col -->

  <div class="col-right col2">
    <h2 class="border">Where are we?</h2>
    <div class="entry justify">
      <p>
        Gnomeslab is based in Lisbon, Portugal, the largest westernmost city in Europe. 
        It lies in the western Iberian Peninsula on the Atlantic Ocean and the Tagus River.
      </p>
      <p>
        In the Internet you can also find us at:
        <ul class="fixlast">
          <li><a href="http://twitter.com/gnomeslab">Twitter</a></li>
        </ul>
      </p>
    </div>
  </div>

  <div class="cl">&nbsp;</div>
</div>

app/views/content_columns/_homepage.html.erb
<div class="cols">
  <div class="cl">&nbsp;</div>

  <!-- Col -->
  <div class="col col2">
    <h2 class="border">What We Do?</h2>
    <div class="entry">
      <p>
        <img src="../images/content/image2.jpg" class="alignright" alt="" />
        We develop websites, applications and services. Our field of expertise goes from major corporate 
        applications to simple websites like this one. No job is too big, no client is too small, 
        if it needs coding, we're on it.
        <br /><a href="about.html" class="more">more</a>
      </p>
    </div>
  </div>
  <!-- End Col -->

  <!-- Col -->
  <div class="col col2">
    <h2 class="border">Meet the team</h2>
    <div class="entry">
      <p>
        <img src="../images/content/image3.jpg" class="alignright" alt="" />
        Seriously, you DONT wanna meet the team. They are homicidal maniacs, they have been known to 
        murder other developers for not commenting their code. Most of them have roots in the Sicilian Mafia. 
        Other noone really knows who they are..... Be affraid, be very affraid!!!
        <br /><a href="about.html" class="more">more</a>
      </p>
    </div>
  </div>
  <!-- End Col -->

  <%= render 'shared/content_box/featured_project' %>

  <div class="cl">&nbsp;</div>
</div>